eureka:
  instance:
    instance-id: intancia1-@project.version@-${spring.application.name}
    #instance-id: intancia2-@project.version@-${spring.application.name}
  client:
    serviceUrl:
      # Direccion a la que se conecta el microservicio con eureka
      defaultZone: http://localhost:8761/eureka  
spring:
  application:
    name: servicio-productos
server:
  port: 8081
  #port: 8082